
services:
  redis:
    image: redis:6.0.9
    restart: "no"
    ports:
      - "6379:6379"
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: local.io/api-transcriptor:local
    restart: "no"
    ports:
      - "8000:8000"
  #ia-worker:
  #  build:
  #    context: ./ia-worker
  #    dockerfile: ./Dockerfile
  #  image: local.io/ia-worker-transcriptor:local
  #  restart: "no"
  #  ports:
  #    - "8001:8000"
  webapp:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile
    image: local.io/webapp-transcriptor:local
    restart: "no"
    ports:
      - "4000:8080"
  slimfaas:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: docker.io/axaguildev/slimfaas:0.24.18
    ports:
      - 5020:5000
    environment:
      - BASE_FUNCTION_URL=http://{function_name}:8000
      - BASE_FUNCTION_POD_URL=http://{function_name}:8000
      - MOCK_KUBERNETES_FUNCTIONS={"Functions":[{"Name":"api","NumberParallelRequest":1},{"Name":"ia-worker","NumberParallelRequest":1}],"Slimfaas":[{"Name":"slimfaas-1"}]}
      - BASE_SLIMDATA_URL=http://localhost:3262/
      - HOSTNAME=slimfaas-1
      - SLIMDATA_CONFIGURATION={"coldStart":"true"}
      - SLIMFAAS_PORTS=5000,5020
      - SLIMFAAS_SUBSCRIBE_EVENTS=transcript=>https://host.docker.internal:8000