networks:
  slimfaas-net:
    driver: bridge

volumes:
  slimfaas_data:

services:
  redis:
    image: redis:6.0.9
    restart: "no"
    ports:
      - "6379:6379"
    labels:
      app: "redis"
      SlimFaas/Function: "true"
      SlimFaas/Namespace: "default"
      SlimFaas/TimeoutSecondBeforeSetReplicasMin: "120"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - slimfaas-net

  api:
    image: ghcr.io/guillaume-chervet/transcriptor-api:0.77.38
    ports:
      - "8040:8000"  
    environment:
      - PYTHON_ENVIRONMENT=production
      - url_slimfaas=http://slimfaas:5020
    labels:
      app: "api"
      SlimFaas/Function: "true"
      SlimFaas/Namespace: "default"
      SlimFaas/SubscribeEvents: "Private:transcript"
      SlimFaas/TimeoutSecondBeforeSetReplicasMin: "120"
      SlimFaas/NumberParallelRequest: "1"
      SlimFaas/DependsOn: "redis"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - slimfaas-net

  ia-worker:
    image: ghcr.io/guillaume-chervet/transcriptor-ia-worker:0.77.38
    ports:
      - "8001:8000"   # host 8001 -> container 8000 (inchangé)
    environment:
      - PYTHON_ENVIRONMENT=production
      - url_slimfaas=http://slimfaas:5020
    labels:
      app: "ia-worker"
      SlimFaas/Function: "true"
      SlimFaas/Namespace: "default"
      SlimFaas/TimeoutSecondBeforeSetReplicasMin: "120"
      SlimFaas/NumberParallelRequest: "1"
      SlimFaas/DependsOn: "redis"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - slimfaas-net

  webapp:
    image: ghcr.io/guillaume-chervet/transcriptor-webapp:0.77.38
    restart: "no"
    ports:
      - "4000:8080"   # inchangé
    networks:
      - slimfaas-net

  slimfaas:
    image: axaguildev/slimfaas:dev
    build:
       context: "C:/github/SlimFaas/"
       dockerfile: ./Dockerfile
    ports:
      - "5020:5020" 
    user: "0:0"
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
      BASE_SLIMDATA_URL: "http://localhost:3262/"
      SLIMDATA_CONFIGURATION: '{"coldStart":"true"}'
      ASPNETCORE_URLS: "http://0.0.0.0:5020" 
      SLIMFAAS_ORCHESTRATOR: "Docker"
      HOSTNAME: "slimfaas-1"
      SLIMDATA_DIRECTORY: "/database-poc-whisper"
      ASPNETCORE_ENVIRONMENT: "Production"
    volumes:
      - slimfaas_data:/database-poc-whisper
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - slimfaas-net
    labels:
      app: "slimfaas"
      com.docker.compose.service: "slimfaas"
    healthcheck:
      # Le /health de SlimFaas écoute sur le port interne 5000
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5020/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
