# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: transcriptor
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        SlimFaas/Function: "true"
        SlimFaas/TimeoutSecondBeforeSetReplicasMin: "1200"
        SlimFaas/NumberParallelRequest: "1"
        SlimFaas/SubscribeEvents: "Private:transcript"
        SlimFaas/ReplicasMin: "0"
        SlimFaas/DependsOn: "redis"
    spec:
      containers:
        - name: api
          image: ghcr.io/guillaume-chervet/transcriptor-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: PYTHON_ENVIRONMENT
              value: "production"
          resources:
            limits:
              memory: "2000Mi"
              cpu: "1000m"
            requests:
              ephemeral-storage: "1000Mi"
              memory: "2000Mi"
              cpu: "1000m"