apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ia-worker-hpa
  namespace: transcriptor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ia-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 120