# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ia-worker
  namespace: transcriptor
  labels:
    app: ia-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ia-worker
  template:
    metadata:
      labels:
        app: ia-worker
      annotations:
        SlimFaas/Function: "true"
        SlimFaas/TimeoutSecondBeforeSetReplicasMin: "1200"
        SlimFaas/NumberParallelRequest: "1"
        SlimFaas/Visibility: "Private"
        SlimFaas/ReplicasMin: "0"
        SlimFaas/DependsOn: "redis"
    spec:
      containers:
        - name: ia-worker
          image: ghcr.io/guillaume-chervet/transcriptor-ia-worker:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8000
          env:
            - name: PYTHON_ENVIRONMENT
              value: "production"
          resources:
            limits:
              memory: "2400Mi"
              cpu: "2000m"
            requests:
              ephemeral-storage: "1000Mi"
              memory: "2400Mi"
              cpu: "2000m"