# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: transcriptor
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        SlimFaas/Function: "true"
        SlimFaas/TimeoutSecondBeforeSetReplicasMin: "1200"
        SlimFaas/NumberParallelRequest: "1"
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
              limits:
                memory: "400Mi"
                cpu: "200m"
              requests:
                ephemeral-storage: "1000Mi"
                memory: "400Mi"
                cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: transcriptor
spec:
    selector:
        app: redis
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379
    type: ClusterIP
