# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: transcriptor
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        SlimFaas/Function: "true"
        SlimFaas/TimeoutSecondBeforeSetReplicasMin: "300"
        SlimFaas/NumberParallelRequest: "1"
        SlimFaas/SubscribeEvents : "Private:transcript"
    spec:
      containers:
        - name: webapp-container
          image: ghcr.io/guillaume-chervet/transcriptor-webapp:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "96Mi"
              cpu: "50m"
            requests:
              ephemeral-storage: "200Mi"
              memory: "96Mi"
              cpu: "50m"