# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80        # Port exposé publiquement
      targetPort: 4000 # Port interne de l'application
  type: LoadBalancer
